# Generated by Django 3.1.4 on 2020-12-20 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('courses', '0002_auto_20201220_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='courseparticipant',
            options={'verbose_name': 'Course participant', 'verbose_name_plural': 'Course participants'},
        ),
        migrations.AlterUniqueTogether(
            name='courseparticipant',
            unique_together={('course', 'student')},
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='courseparticipant',
            table='courses_course_participant',
        ),
    ]
