# Generated by Django 3.1.4 on 2020-12-20 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201220_2218'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courseparticipant',
            table='course_participant',
        ),
    ]
